----------------------------------------- 1. Очистка данных из STG -------------------------------------------

DELETE
FROM DEMIPT.ANBO_STG_PSSPRT_BLCKLST;


DELETE
FROM DEMIPT.ANBO_STG_TRANSACTIONS;


DELETE
FROM DEMIPT.ANBO_STG_TERMINALS;


DELETE
FROM DEMIPT.ANBO_STG_TERMINALS_DRFT;


DELETE
FROM DEMIPT.ANBO_STG_BANK_ACCOUNTS;


DELETE
FROM DEMIPT.ANBO_STG_BANK_CARDS;


DELETE
FROM DEMIPT.ANBO_STG_BANK_CLIENTS;


DELETE
FROM DEMIPT.ANBO_STG_BANK_ACCOUNTS_DEL;


DELETE
FROM DEMIPT.ANBO_STG_BANK_CARDS_DEL;


DELETE
FROM DEMIPT.ANBO_STG_BANK_CLIENTS_DEL;


DELETE
FROM DEMIPT.ANBO_STG_TERMINALS_DEL;

# ------------------------------------------- 2. Захват данных из источников. ------------------------------------------

INSERT INTO DEMIPT.ANBO_STG_BANK_ACCOUNTS(ACCOUNT, VALID_TO, CLIENT, CREATE_DT, UPDATE_DT)
SELECT ACCOUNT,
       VALID_TO,
       CLIENT,
       CREATE_DT,
       UPDATE_DT
FROM BANK.ACCOUNTS
WHERE COALESCE(UPDATE_DT, CREATE_DT) >
    (SELECT LAST_UPDATE
     FROM DEMIPT.ANBO_META_LOADING
     WHERE DBNAME = 'DEMIPT'
       AND TABLENAME = 'ANBO_DWH_DIM_ACCOUNTS_HIST' );


INSERT INTO DEMIPT.ANBO_STG_BANK_CARDS(CARD_NUM, ACCOUNT, CREATE_DT, UPDATE_DT)
SELECT CARD_NUM,
       ACCOUNT,
       CREATE_DT,
       UPDATE_DT
FROM BANK.CARDS
WHERE COALESCE(UPDATE_DT, CREATE_DT) >
    (SELECT LAST_UPDATE
     FROM DEMIPT.ANBO_META_LOADING
     WHERE DBNAME = 'DEMIPT'
       AND TABLENAME = 'ANBO_DWH_DIM_CARDS_HIST' );


INSERT INTO DEMIPT.ANBO_STG_BANK_CLIENTS(CLIENT_ID, LAST_NAME, FIRST_NAME, PATRONYMIC, DATE_OF_BIRTH, PASSPORT_NUM, PASSPORT_VALID_TO, PHONE, CREATE_DT, UPDATE_DT)
SELECT CLIENT_ID,
       LAST_NAME,
       FIRST_NAME,
       PATRONYMIC,
       DATE_OF_BIRTH,
       PASSPORT_NUM,
       PASSPORT_VALID_TO,
       PHONE,
       CREATE_DT,
       UPDATE_DT
FROM BANK.CLIENTS
WHERE COALESCE(UPDATE_DT, CREATE_DT) >
    (SELECT LAST_UPDATE
     FROM DEMIPT.ANBO_META_LOADING
     WHERE DBNAME = 'DEMIPT'
       AND TABLENAME = 'ANBO_DWH_DIM_CLIENTS_HIST' );


INSERT INTO DEMIPT.ANBO_STG_TERMINALS (TERMINAL_ID, TERMINAL_TYPE, TERMINAL_CITY, TERMINAL_ADDRESS, CREATE_DT, UPDATE_DT)
SELECT t1.TERMINAL_ID,
       t1.TERMINAL_TYPE,
       t1.TERMINAL_CITY,
       t1.TERMINAL_ADDRESS,
       MIN(t2.EFFECTIVE_FROM) OVER (PARTITION BY t2.TERMINAL_ID
                                    ORDER BY t2.EFFECTIVE_FROM) AS CREATE_DT,
                                   TO_DATE(t1.UPLOAD_DT, 'DD.MM.YYYY')
FROM ANBO_STG_TERMINALS_DRFT t1
LEFT JOIN ANBO_DWH_DIM_TERMINALS_HIST t2 ON t1.terminal_id = t2.TERMINAL_ID
WHERE t2.EFFECTIVE_TO = TO_DATE('31.12.2021', 'DD.MM.YYYY')
  AND t1.terminal_type != t2.terminal_type
  OR t1.terminal_city != t2.terminal_city
  OR t1.terminal_type != t2.terminal_type
  OR t1.TERMINAL_ADDRESS != t2.terminal_address;


INSERT INTO DEMIPT.ANBO_STG_TERMINALS (TERMINAL_ID, TERMINAL_TYPE, TERMINAL_CITY, TERMINAL_ADDRESS, CREATE_DT, UPDATE_DT)
SELECT t1.TERMINAL_ID,
       t1.TERMINAL_TYPE,
       t1.TERMINAL_CITY,
       t1.TERMINAL_ADDRESS,
       TO_DATE(t1.UPLOAD_DT, 'DD.MM.YYYY'),
       NULL
FROM ANBO_STG_TERMINALS_DRFT t1
LEFT JOIN ANBO_DWH_DIM_TERMINALS_HIST t2 ON t1.terminal_id = t2.TERMINAL_ID
WHERE t2.terminal_id IS NULL;

# ------------------------------------ 3. Загрузка данных из стейджинга в хранилище ------------------------------------

INSERT INTO DEMIPT.ANBO_DWH_FACT_TRANSACTIONS(TRANS_ID, TRANS_DATE, CARD_NUM, OPER_TYPE, AMT, OPER_RESULT, TERMINAL)
SELECT TRANSACTION_ID,
       TO_DATE(TRANSACTION_DATE, 'YYYY-MM-DD HH24:MI:SS'),
       CARD_NUM,
       OPER_TYPE,
       AMOUNT,
       OPER_RESULT,
       TERMINAL
FROM DEMIPT.ANBO_STG_TRANSACTIONS;


INSERT INTO ANBO_DWH_FACT_PSSPRT_BLCKLST(PASSPORT_NUM, ENTRY_DT)
SELECT PASSPORT_NUM,
       TO_DATE(ENTRY_DT, 'YYYY-MM-DD')
FROM ANBO_STG_PSSPRT_BLCKLST
WHERE TO_DATE(ENTRY_DT, 'YYYY-MM-DD') >
    (SELECT LAST_UPDATE
     FROM ANBO_META_LOADING
     WHERE DBNAME = 'DEMIPT'
       AND TABLENAME = 'ANBO_DWH_FACT_PSSPRT_BLCKLST' );


INSERT INTO DEMIPT.ANBO_DWH_DIM_TERMINALS_HIST(TERMINAL_ID, TERMINAL_TYPE, TERMINAL_CITY, TERMINAL_ADDRESS, EFFECTIVE_FROM, EFFECTIVE_TO, DELETED_FLG)
SELECT TERMINAL_ID,
       TERMINAL_TYPE,
       TERMINAL_CITY,
       TERMINAL_ADDRESS,
       COALESCE(UPDATE_DT, CREATE_DT),
       TO_DATE('2999-12-31', 'YYYY-MM-DD'),
       'N'
FROM DEMIPT.ANBO_STG_TERMINALS;


MERGE INTO DEMIPT.ANBO_DWH_DIM_TERMINALS_HIST tgt USING DEMIPT.ANBO_STG_TERMINALS src ON (tgt.TERMINAL_ID = src.TERMINAL_ID
                                                                                          AND tgt.EFFECTIVE_FROM < COALESCE(src.UPDATE_DT, src.CREATE_DT)) WHEN matched THEN
UPDATE
SET tgt.EFFECTIVE_TO = COALESCE(src.UPDATE_DT, src.CREATE_DT) - interval '1' SECOND;


WHERE tgt.EFFECTIVE_TO = TO_DATE('2999-12-31', 'YYYY-MM-DD')
  INSERT INTO DEMIPT.ANBO_DWH_DIM_ACCOUNTS_HIST(ACCOUNT_NUM, VALID_TO, CLIENT, EFFECTIVE_FROM, EFFECTIVE_TO, DELETED_FLG)
SELECT ACCOUNT,
       VALID_TO,
       CLIENT,
       COALESCE(UPDATE_DT, CREATE_DT),
       TO_DATE('2999-12-31', 'YYYY-MM-DD'),
       'N'
FROM DEMIPT.ANBO_STG_BANK_ACCOUNTS;


MERGE INTO DEMIPT.ANBO_DWH_DIM_ACCOUNTS_HIST tgt USING DEMIPT.ANBO_STG_BANK_ACCOUNTS src ON (tgt.ACCOUNT_NUM = src.ACCOUNT
                                                                                             AND tgt.EFFECTIVE_FROM < COALESCE(src.UPDATE_DT, src.CREATE_DT)) WHEN matched THEN
UPDATE
SET tgt.EFFECTIVE_TO = COALESCE(src.UPDATE_DT, src.CREATE_DT) - interval '1' SECOND
WHERE tgt.EFFECTIVE_TO = TO_DATE('2999-12-31', 'YYYY-MM-DD');


INSERT INTO DEMIPT.ANBO_DWH_DIM_CARDS_HIST(CARD_NUM, ACCOUNT_NUM, EFFECTIVE_FROM, EFFECTIVE_TO, DELETED_FLG)
SELECT CARD_NUM,
       ACCOUNT,
       COALESCE(UPDATE_DT, CREATE_DT),
       TO_DATE('2999-12-31', 'YYYY-MM-DD'),
       'N'
FROM DEMIPT.ANBO_STG_BANK_CARDS;


MERGE INTO DEMIPT.ANBO_DWH_DIM_CARDS_HIST tgt USING DEMIPT.ANBO_STG_BANK_CARDS src ON (tgt.CARD_NUM = src.CARD_NUM
                                                                                       AND tgt.EFFECTIVE_FROM < COALESCE(src.UPDATE_DT, src.CREATE_DT)) WHEN matched THEN
UPDATE
SET tgt.EFFECTIVE_TO = COALESCE(src.UPDATE_DT, src.CREATE_DT) - interval '1' SECOND;


WHERE tgt.EFFECTIVE_TO = TO_DATE('2999-12-31', 'YYYY-MM-DD');


INSERT INTO DEMIPT.ANBO_DWH_DIM_CLIENTS_HIST(CLIENT_ID, LAST_NAME, FIRST_NAME, PATRONYMIC, DATE_OF_BIRTH, PASSPORT_NUM, PASSPORT_VALID_TO, PHONE, EFFECTIVE_FROM, EFFECTIVE_TO, DELETED_FLG)
SELECT CLIENT_ID,
       LAST_NAME,
       FIRST_NAME,
       PATRONYMIC,
       DATE_OF_BIRTH,
       PASSPORT_NUM,
       PASSPORT_VALID_TO,
       PHONE,
       COALESCE(UPDATE_DT, CREATE_DT),
       TO_DATE('2999-12-31', 'YYYY-MM-DD'),
       'N'
FROM DEMIPT.ANBO_STG_BANK_CLIENTS;


MERGE INTO DEMIPT.ANBO_DWH_DIM_CLIENTS_HIST tgt USING DEMIPT.ANBO_STG_BANK_CLIENTS src ON (tgt.CLIENT_ID = src.CLIENT_ID
                                                                                           AND tgt.EFFECTIVE_FROM < COALESCE(src.UPDATE_DT, src.CREATE_DT)) WHEN matched THEN
UPDATE
SET tgt.EFFECTIVE_TO = COALESCE(src.UPDATE_DT, src.CREATE_DT) - interval '1' SECOND
WHERE tgt.EFFECTIVE_TO = TO_DATE('2999-12-31', 'YYYY-MM-DD');

# ------------------------------------- 4. Захват ключей для проверки удалений  ----------------------------------------

INSERT INTO DEMIPT.ANBO_STG_TERMINALS_DEL (TERMINAL_ID)
SELECT TERMINAL_ID
FROM DEMIPT.ANBO_STG_TERMINALS_DRFT;


INSERT INTO DEMIPT.ANBO_STG_BANK_ACCOUNTS_DEL (ACCOUNT)
SELECT ACCOUNT
FROM BANK.ACCOUNTS;


INSERT INTO DEMIPT.ANBO_STG_BANK_CARDS_DEL (CARD_NUM)
SELECT CARD_NUM
FROM BANK.CARDS;


INSERT INTO DEMIPT.ANBO_STG_BANK_CLIENTS_DEL (CLIENT_ID)
SELECT CLIENT_ID
FROM BANK.CLIENTS;

# ----------------------------------- 5. Удаляем удаленные записи в целевой таблице ------------------------------------

INSERT INTO DEMIPT.ANBO_DWH_DIM_TERMINALS_HIST(TERMINAL_ID, TERMINAL_TYPE, TERMINAL_CITY, TERMINAL_ADDRESS, EFFECTIVE_FROM, EFFECTIVE_TO, DELETED_FLG)
SELECT t.TERMINAL_ID,
       t.TERMINAL_TYPE,
       t.TERMINAL_CITY,
       t.TERMINAL_ADDRESS,
       sysdate,
       TO_DATE('2999-12-31', 'YYYY-MM-DD'),
       'Y'
FROM ANBO_DWH_DIM_TERMINALS_HIST t
LEFT JOIN ANBO_STG_TERMINALS_DEL s ON t.TERMINAL_ID = s.TERMINAL_ID
WHERE s.TERMINAL_ID IS NULL
  AND EFFECTIVE_TO = TO_DATE('2999-12-31', 'YYYY-MM-DD')
  AND deleted_flg = 'N';


UPDATE DEMIPT.ANBO_DWH_DIM_TERMINALS_HIST
SET EFFECTIVE_TO = sysdate - interval '1' SECOND
WHERE TERMINAL_ID in
    (SELECT t.TERMINAL_ID
     FROM ANBO_DWH_DIM_TERMINALS_HIST t
     LEFT JOIN ANBO_STG_TERMINALS_DEL s ON t.TERMINAL_ID = s.TERMINAL_ID
     WHERE s.TERMINAL_ID IS NULL
       AND EFFECTIVE_TO = TO_DATE('2999-12-31', 'YYYY-MM-DD')
       AND deleted_flg = 'N')
  AND EFFECTIVE_TO = TO_DATE('2999-12-31', 'YYYY-MM-DD')
  AND EFFECTIVE_FROM < sysdate
  AND deleted_flg = 'N';


INSERT INTO DEMIPT.ANBO_DWH_DIM_ACCOUNTS_HIST(ACCOUNT_NUM, VALID_TO, CLIENT, EFFECTIVE_FROM, EFFECTIVE_TO, DELETED_FLG)
SELECT t.ACCOUNT_NUM,
       t.VALID_TO,
       t.CLIENT,
       sysdate,
       TO_DATE('2999-12-31', 'YYYY-MM-DD'),
       'Y'
FROM ANBO_DWH_DIM_ACCOUNTS_HIST t
LEFT JOIN ANBO_STG_BANK_ACCOUNTS_DEL s ON t.ACCOUNT_NUM = s.ACCOUNT
WHERE s.ACCOUNT IS NULL
  AND EFFECTIVE_TO = TO_DATE('2999-12-31', 'YYYY-MM-DD')
  AND deleted_flg = 'N';


UPDATE DEMIPT.ANBO_DWH_DIM_ACCOUNTS_HIST
SET EFFECTIVE_TO = sysdate - interval '1' SECOND
WHERE ACCOUNT_NUM in
    (SELECT t.ACCOUNT_NUM
     FROM ANBO_DWH_DIM_ACCOUNTS_HIST t
     LEFT JOIN ANBO_STG_BANK_ACCOUNTS_DEL s ON t.ACCOUNT_NUM = s.ACCOUNT
     WHERE s.ACCOUNT IS NULL
       AND EFFECTIVE_TO = TO_DATE('2999-12-31', 'YYYY-MM-DD')
       AND deleted_flg = 'N')
  AND EFFECTIVE_TO = TO_DATE('2999-12-31', 'YYYY-MM-DD')
  AND EFFECTIVE_FROM < sysdate
  AND deleted_flg = 'N';


INSERT INTO DEMIPT.ANBO_DWH_DIM_CARDS_HIST(CARD_NUM, ACCOUNT_NUM, EFFECTIVE_FROM, EFFECTIVE_TO, DELETED_FLG)
SELECT t.CARD_NUM,
       t.ACCOUNT_NUM,
       sysdate,
       TO_DATE('2999-12-31', 'YYYY-MM-DD'),
       'Y'
FROM ANBO_DWH_DIM_CARDS_HIST t
LEFT JOIN ANBO_STG_BANK_CARDS_DEL s ON t.CARD_NUM = s.CARD_NUM
WHERE s.CARD_NUM IS NULL
  AND EFFECTIVE_TO = TO_DATE('2999-12-31', 'YYYY-MM-DD')
  AND deleted_flg = 'N';


UPDATE DEMIPT.ANBO_DWH_DIM_CARDS_HIST
SET EFFECTIVE_TO = sysdate - interval '1' SECOND
WHERE CARD_NUM in
    (SELECT t.CARD_NUM
     FROM ANBO_DWH_DIM_CARDS_HIST t
     LEFT JOIN ANBO_STG_BANK_CARDS_DEL s ON t.CARD_NUM = s.CARD_NUM
     WHERE s.CARD_NUM IS NULL
       AND EFFECTIVE_TO = TO_DATE('2999-12-31', 'YYYY-MM-DD')
       AND deleted_flg = 'N')
  AND EFFECTIVE_TO = TO_DATE('2999-12-31', 'YYYY-MM-DD')
  AND EFFECTIVE_FROM < sysdate
  AND deleted_flg = 'N';


INSERT INTO DEMIPT.ANBO_DWH_DIM_CLIENTS_HIST(CLIENT_ID, LAST_NAME, FIRST_NAME, PATRONYMIC, DATE_OF_BIRTH, PASSPORT_NUM, PASSPORT_VALID_TO, PHONE, EFFECTIVE_FROM, EFFECTIVE_TO, DELETED_FLG)
SELECT t.CLIENT_ID,
       t.LAST_NAME,
       t.FIRST_NAME,
       t.PATRONYMIC,
       t.DATE_OF_BIRTH,
       t.PASSPORT_NUM,
       t.PASSPORT_VALID_TO,
       t.PHONE,
       sysdate,
       TO_DATE('2999-12-31', 'YYYY-MM-DD'),
       'Y'
FROM ANBO_DWH_DIM_CLIENTS_HIST t
LEFT JOIN ANBO_STG_BANK_CLIENTS_DEL s ON t.CLIENT_ID = s.CLIENT_ID
WHERE s.CLIENT_ID IS NULL
  AND EFFECTIVE_TO = TO_DATE('2999-12-31', 'YYYY-MM-DD')
  AND deleted_flg = 'N';


UPDATE DEMIPT.ANBO_DWH_DIM_CLIENTS_HIST
SET EFFECTIVE_TO = sysdate - interval '1' SECOND
WHERE CLIENT_ID in
    (SELECT t.CLIENT_ID
     FROM ANBO_DWH_DIM_CLIENTS_HIST t
     LEFT JOIN ANBO_STG_BANK_CLIENTS_DEL s ON t.CLIENT_ID = s.CLIENT_ID
     WHERE s.CLIENT_ID IS NULL
       AND EFFECTIVE_TO = TO_DATE('2999-12-31', 'YYYY-MM-DD')
       AND deleted_flg = 'N')
  AND EFFECTIVE_TO = TO_DATE('2999-12-31', 'YYYY-MM-DD')
  AND EFFECTIVE_FROM < sysdate
  AND deleted_flg = 'N';

# ------------------------------- 6. Обновляем метаданные - дату максимальной загрузуки --------------------------------

UPDATE DEMIPT.ANBO_META_LOADING
SET last_update =
  (SELECT MAX(TO_DATE(UPLOAD_DT, 'DD.MM.YYYY'))
   FROM DEMIPT.ANBO_STG_TERMINALS_DRFT)
WHERE dbname = 'DEMIPT'
  AND tablename = 'ANBO_DWH_DIM_TERMINALS_HIST'
  AND
    (SELECT MAX(TO_DATE(UPLOAD_DT, 'DD.MM.YYYY'))
     FROM DEMIPT.ANBO_STG_TERMINALS_DRFT) IS NOT NULL;


UPDATE DEMIPT.ANBO_META_LOADING
SET last_update =
  (SELECT MAX(TO_DATE(ENTRY_DT, 'YYYY-MM-DD'))
   FROM DEMIPT.ANBO_STG_PSSPRT_BLCKLST)
WHERE dbname = 'DEMIPT'
  AND tablename = 'ANBO_DWH_FACT_PSSPRT_BLCKLST'
  AND
    (SELECT MAX(TO_DATE(ENTRY_DT, 'YYYY-MM-DD'))
     FROM DEMIPT.ANBO_STG_PSSPRT_BLCKLST) IS NOT NULL;


UPDATE DEMIPT.ANBO_META_LOADING
SET last_update =
  (SELECT MAX(COALESCE(UPDATE_DT, CREATE_DT))
   FROM DEMIPT.ANBO_STG_BANK_ACCOUNTS)
WHERE dbname = 'DEMIPT'
  AND tablename = 'ANBO_DWH_DIM_ACCOUNTS_HIST'
  AND
    (SELECT MAX(COALESCE(UPDATE_DT, CREATE_DT))
     FROM DEMIPT.ANBO_STG_BANK_ACCOUNTS) IS NOT NULL;


UPDATE DEMIPT.ANBO_META_LOADING
SET last_update =
  (SELECT MAX(COALESCE(UPDATE_DT, CREATE_DT))
   FROM DEMIPT.ANBO_STG_BANK_CARDS)
WHERE dbname = 'DEMIPT'
  AND tablename = 'ANBO_DWH_DIM_CARDS_HIST'
  AND
    (SELECT MAX(COALESCE(UPDATE_DT, CREATE_DT))
     FROM DEMIPT.ANBO_STG_BANK_CARDS) IS NOT NULL;


UPDATE DEMIPT.ANBO_META_LOADING
SET last_update =
  (SELECT MAX(COALESCE(UPDATE_DT, CREATE_DT))
   FROM DEMIPT.ANBO_STG_BANK_CLIENTS)
WHERE dbname = 'DEMIPT'
  AND tablename = 'ANBO_DWH_DIM_CLIENTS_HIST'
  AND
    (SELECT MAX(COALESCE(UPDATE_DT, CREATE_DT))
     FROM DEMIPT.ANBO_STG_BANK_CLIENTS) IS NOT NULL;


UPDATE DEMIPT.ANBO_META_LOADING
SET last_update =
  (SELECT MAX(COALESCE(UPDATE_DT, CREATE_DT))
   FROM DEMIPT.ANBO_STG_BANK_CARDS)
WHERE dbname = 'DEMIPT'
  AND tablename = 'ANBO_DWH_DIM_CARDS_HIST'
  AND
    (SELECT MAX(COALESCE(UPDATE_DT, CREATE_DT))
     FROM DEMIPT.ANBO_STG_BANK_CARDS) IS NOT NULL;

# ---------------------------------------------- 7. Фиксируем транзакцию ----------------------------------------------

COMMIT;