-- 1. Совершение операции при просроченном или заблокированном паспорте.
-- (1) Транзакции только за этот день и предыдущий, накоплением.
-- (2) Данные таблицы измерения актуальные только на этот момент времени.
-- (3) Не удаленные строки.
-- (4) Последний день срока действия паспорта - не преступление.
-- (5) Убираем строки полные дубли.

INSERT INTO DEMIPT.ANBO_REP_FRAUD ( EVENT_ID, PASSPORT, FIO, PHONE, EVENT_TYPE, REPORT_DT) 
SELECT 
    t1.TRANS_DATE,
    t4.PASSPORT_NUM,
    t4.LAST_NAME||' '||t4.FIRST_NAME||' '||t4.PATRONYMIC,
    t4.PHONE,
    '1',
    TO_DATE( '03.03.2021 23:59:59', 'DD.MM.YYYY HH24:MI:SS' )
FROM DEMIPT.ANBO_DWH_FACT_TRANSACTIONS T1
INNER JOIN DEMIPT.ANBO_DWH_DIM_CARDS_HIST T2
ON T1.CARD_NUM = T2.CARD_NUM
AND t1.TRANS_DATE <= TO_DATE( '03.03.2021 23:59:59', 'DD.MM.YYYY HH24:MI:SS' ) -- (1)
AND TO_DATE( '03.03.2021 23:59:59', 'DD.MM.YYYY HH24:MI:SS' ) BETWEEN T2.EFFECTIVE_FROM AND T2.EFFECTIVE_TO --(2)
AND T2.DELETED_FLG = 'N' -- (3)
INNER JOIN DEMIPT.ANBO_DWH_DIM_ACCOUNTS_HIST T3
ON T2.ACCOUNT_NUM = T3.ACCOUNT_NUM
AND TO_DATE( '03.03.2021 23:59:59', 'DD.MM.YYYY HH24:MI:SS' ) BETWEEN T3.EFFECTIVE_FROM AND T3.EFFECTIVE_TO -- (2)
AND T3.DELETED_FLG = 'N' -- (3)
INNER JOIN DEMIPT.ANBO_DWH_DIM_CLIENTS_HIST T4
ON T3.CLIENT = T4.CLIENT_ID
AND TO_DATE( '03.03.2021 23:59:59', 'DD.MM.YYYY HH24:MI:SS' ) BETWEEN T4.EFFECTIVE_FROM AND T4.EFFECTIVE_TO -- (2)
AND T4.DELETED_FLG = 'N' -- (3)
WHERE 1=1
AND T4.PASSPORT_NUM IN (SELECT PASSPORT_NUM FROM ANBO_DWH_FACT_PSSPRT_BLCKLST WHERE ENTRY_DT <= TO_DATE( '03.03.2021 23:59:59', 'DD.MM.YYYY HH24:MI:SS' ) )
OR T4.PASSPORT_VALID_TO < TO_DATE( '03.03.2021 23:59:59', 'DD.MM.YYYY HH24:MI:SS' ); -- (4)

-- 2. Совершение операции при недействующем договоре

INSERT INTO DEMIPT.ANBO_REP_FRAUD ( EVENT_ID, PASSPORT, FIO, PHONE, EVENT_TYPE, REPORT_DT) 
SELECT DISTINCT
    t1.TRANS_DATE,
    t4.PASSPORT_NUM,
    t4.LAST_NAME||' '||t4.FIRST_NAME||' '||t4.PATRONYMIC,
    t4.PHONE,
    '2',
    TO_DATE( '03.03.2021 23:59:59', 'DD.MM.YYYY HH24:MI:SS' )
FROM DEMIPT.ANBO_DWH_FACT_TRANSACTIONS T1
INNER JOIN DEMIPT.ANBO_DWH_DIM_CARDS_HIST T2
ON T1.CARD_NUM = T2.CARD_NUM
AND t1.TRANS_DATE <= TO_DATE( '03.03.2021 23:59:59', 'DD.MM.YYYY HH24:MI:SS' ) -- (1)
AND TO_DATE( '03.03.2021 23:59:59', 'DD.MM.YYYY HH24:MI:SS' ) BETWEEN T2.EFFECTIVE_FROM AND T2.EFFECTIVE_TO --(2)
AND T2.DELETED_FLG = 'N' -- (3)
INNER JOIN DEMIPT.ANBO_DWH_DIM_ACCOUNTS_HIST T3
ON T2.ACCOUNT_NUM = T3.ACCOUNT_NUM
AND TO_DATE( '03.03.2021 23:59:59', 'DD.MM.YYYY HH24:MI:SS' ) BETWEEN T3.EFFECTIVE_FROM AND T3.EFFECTIVE_TO -- (2)
AND T3.DELETED_FLG = 'N' -- (3)
INNER JOIN DEMIPT.ANBO_DWH_DIM_CLIENTS_HIST T4
ON T3.CLIENT = T4.CLIENT_ID
AND TO_DATE( '03.03.2021 23:59:59', 'DD.MM.YYYY HH24:MI:SS' ) BETWEEN T4.EFFECTIVE_FROM AND T4.EFFECTIVE_TO -- (2)
AND T4.DELETED_FLG = 'N' -- (3)
WHERE 1=1
AND T3.VALID_TO < TO_DATE( '03.03.2021 23:59:59', 'DD.MM.YYYY HH24:MI:SS' );
